export enum Currency {
  RUR = 'RUR',
  USD = 'USD',
  EUR = 'EUR',
  CNY = 'CNY',
  GBP = 'GBP',
  CHF = 'CHF',
  JPY = 'JPY',
  KZT = 'KZT',
  UAH = 'UAH',
  CAD = 'CAD',
  SEK = 'SEK',
  BYR = 'BYR',
  DEP = 'DEP',
  NOK = 'NOK',
  PLN = 'PLN',
  AUD = 'AUD',
  BYN = 'BYN',
  DKK = 'DKK',
  SGD = 'SGD',
  AZM = 'AZM',
  AED = 'AED',
  AFA = 'AFA',
  AFN = 'AFN',
  ALL = 'ALL',
  AMD = 'AMD',
  ANG = 'ANG',
  AOA = 'AOA',
  ARS = 'ARS',
  ATS = 'ATS',
  AWG = 'AWG',
  AZN = 'AZN',
  BBD = 'BBD',
  BDT = 'BDT',
  BEF = 'BEF',
  BGL = 'BGL',
  BGN = 'BGN',
  BHD = 'BHD',
  BIF = 'BIF',
  BMD = 'BMD',
  BND = 'BND',
  BOB = 'BOB',
  BRL = 'BRL',
  BSD = 'BSD',
  BTN = 'BTN',
  BWP = 'BWP',
  BZD = 'BZD',
  CDF = 'CDF',
  CLP = 'CLP',
  COP = 'COP',
  COU = 'COU',
  CRC = 'CRC',
  CUC = 'CUC',
  CUP = 'CUP',
  CVE = 'CVE',
  CYP = 'CYP',
  CZK = 'CZK',
  DJF = 'DJF',
  DOP = 'DOP',
  DZD = 'DZD',
  ECS = 'ECS',
  EEK = 'EEK',
  EGP = 'EGP',
  ERN = 'ERN',
  ESP = 'ESP',
  ETB = 'ETB',
  FIM = 'FIM',
  FJD = 'FJD',
  FKP = 'FKP',
  FRF = 'FRF',
  GEL = 'GEL',
  GHC = 'GHC',
  GHS = 'GHS',
  GIP = 'GIP',
  GMD = 'GMD',
  GNF = 'GNF',
  GRD = 'GRD',
  GTQ = 'GTQ',
  GWP = 'GWP',
  GYD = 'GYD',
  HKD = 'HKD',
  HNL = 'HNL',
  HRK = 'HRK',
  HTG = 'HTG',
  HUF = 'HUF',
  IDR = 'IDR',
  IEP = 'IEP',
  ILS = 'ILS',
  INR = 'INR',
  IQD = 'IQD',
  IRR = 'IRR',
  ISK = 'ISK',
  ITL = 'ITL',
  JMD = 'JMD',
  JOD = 'JOD',
  KES = 'KES',
  KGS = 'KGS',
  KHR = 'KHR',
  KMF = 'KMF',
  KPW = 'KPW',
  KRW = 'KRW',
  KWD = 'KWD',
  KYD = 'KYD',
  LAK = 'LAK',
  LBP = 'LBP',
  LKR = 'LKR',
  LRD = 'LRD',
  LSL = 'LSL',
  LTL = 'LTL',
  LUF = 'LUF',
  LVL = 'LVL',
  LYD = 'LYD',
  MAD = 'MAD',
  MDL = 'MDL',
  MGA = 'MGA',
  MGF = 'MGF',
  MKD = 'MKD',
  MMK = 'MMK',
  MNT = 'MNT',
  MOP = 'MOP',
  MRO = 'MRO',
  MTL = 'MTL',
  MUR = 'MUR',
  MVR = 'MVR',
  MWK = 'MWK',
  MXN = 'MXN',
  MYR = 'MYR',
  MZM = 'MZM',
  MZN = 'MZN',
  NAD = 'NAD',
  NGN = 'NGN',
  NIO = 'NIO',
  NLG = 'NLG',
  NPR = 'NPR',
  NZD = 'NZD',
  OMR = 'OMR',
  PAB = 'PAB',
  PEN = 'PEN',
  PGK = 'PGK',
  PHP = 'PHP',
  PKR = 'PKR',
  PYG = 'PYG',
  QAR = 'QAR',
  ROL = 'ROL',
  RON = 'RON',
  RSD = 'RSD',
  RUB = 'RUB',
  RWF = 'RWF',
  SAR = 'SAR',
  SBD = 'SBD',
  SCR = 'SCR',
  SDD = 'SDD',
  SDG = 'SDG',
  SHP = 'SHP',
  SIT = 'SIT',
  SKK = 'SKK',
  SLL = 'SLL',
  SOS = 'SOS',
  SRD = 'SRD',
  SRG = 'SRG',
  SSP = 'SSP',
  STD = 'STD',
  SVC = 'SVC',
  SYP = 'SYP',
  SZL = 'SZL',
  THB = 'THB',
  TJS = 'TJS',
  TMM = 'TMM',
  TMT = 'TMT',
  TND = 'TND',
  TOP = 'TOP',
  TPE = 'TPE',
  TRL = 'TRL',
  TRY = 'TRY',
  TTD = 'TTD',
  TWD = 'TWD',
  TZS = 'TZS',
  UGX = 'UGX',
  UYI = 'UYI',
  UYU = 'UYU',
  UZS = 'UZS',
  VEB = 'VEB',
  VEF = 'VEF',
  VND = 'VND',
  VUV = 'VUV',
  WST = 'WST',
  XAF = 'XAF',
  XCD = 'XCD',
  XDR = 'XDR',
  XOF = 'XOF',
  XPF = 'XPF',
  YER = 'YER',
  YUM = 'YUM',
  ZAR = 'ZAR',
  ZMK = 'ZMK',
  ZMW = 'ZMW',
  ZWD = 'ZWD',
  ZWL = 'ZWL',
  ВАМ = 'ВАМ',
  РТЕ = 'РТЕ'
}

// https://www.w3schools.com/charsets/ref_utf_currency.asp
// https://www.htmlsymbols.xyz/currency-symbols
export const Currencies = [
  { currencyId: 'AED', name: 'Дирхам (ОАЭ)', charCode: [68, 72] },
  { currencyId: 'AFA', name: 'АФГАНИ' },
  { currencyId: 'AFN', name: 'Афгани' },
  { currencyId: 'ALL', name: 'Лек' },
  { currencyId: 'AMD', name: 'Армянский драм' },
  { currencyId: 'ANG', name: 'Нидерландский антильский гульден' },
  { currencyId: 'AOA', name: 'Кванза' },
  { currencyId: 'ARS', name: 'Аргентинское песо' },
  { currencyId: 'ATS', name: 'ШИЛЛИНГ' },
  { currencyId: 'AUD', name: 'Австралийский доллар', charCode: [65, 36] },
  { currencyId: 'AWG', name: 'Арубанский флорин' },
  { currencyId: 'AZM', name: 'АЗЕРБАЙДЖАНСКИЙ МАНАТ' },
  { currencyId: 'AZN', name: 'Азербайджанский манат' },
  { currencyId: 'BBD', name: 'Барбадосский доллар' },
  { currencyId: 'BDT', name: 'Така' },
  { currencyId: 'BEF', name: 'БЕЛЬГИЙСКИЙ ФРАНК' },
  { currencyId: 'BGL', name: 'ЛЕВ' },
  { currencyId: 'BGN', name: 'Болгарский лев', charCode: [1083, 1074] },
  { currencyId: 'BHD', name: 'Бахрейнский динар' },
  { currencyId: 'BIF', name: 'Бурундийский франк' },
  { currencyId: 'BMD', name: 'Бермудский доллар' },
  { currencyId: 'BND', name: 'Брунейский доллар' },
  { currencyId: 'BOB', name: 'Боливиано' },
  { currencyId: 'BRL', name: 'Бразильский реал' },
  { currencyId: 'BSD', name: 'Багамский доллар' },
  { currencyId: 'BTN', name: 'Нгултрум' },
  { currencyId: 'BWP', name: 'Пула' },
  { currencyId: 'BYN', name: 'БЕЛОРУССКИЙ РУБЛЬ', charCode: [1088, 46] },
  { currencyId: 'BYR', name: 'Белорусский рубль' },
  { currencyId: 'BZD', name: 'Белизский доллар' },
  { currencyId: 'CAD', name: 'Канадский доллар', charCode: [67, 36] },
  { currencyId: 'CDF', name: 'Конголезский франк' },
  { currencyId: 'CHF', name: 'Швейцарский франк', charCode: [8355] },
  { currencyId: 'CLP', name: 'Чилийское песо' },
  { currencyId: 'CNY', name: 'Юань', charCode: [65509] },
  { currencyId: 'COP', name: 'Колумбийское песо' },
  { currencyId: 'COU', name: 'Единица реальной стоимости' },
  { currencyId: 'CRC', name: 'Костариканский колон' },
  { currencyId: 'CUC', name: 'Конвертируемое песо' },
  { currencyId: 'CUP', name: 'Кубинское песо' },
  { currencyId: 'CVE', name: 'Эскудо Кабо-Верде' },
  { currencyId: 'CYP', name: 'КИПРСКИЙ ФУНТ' },
  { currencyId: 'CZK', name: 'Чешская крона', charCode: [75, 269] },
  { currencyId: 'DJF', name: 'Франк Джибути' },
  { currencyId: 'DKK', name: 'Датская крона', charCode: [107, 114] },
  { currencyId: 'DOP', name: 'Доминиканское песо' },
  { currencyId: 'DZD', name: 'Алжирский динар' },
  { currencyId: 'ECS', name: 'СУКРЕ' },
  { currencyId: 'EEK', name: 'КРОНА' },
  { currencyId: 'EGP', name: 'Египетский фунт' },
  { currencyId: 'ERN', name: 'Накфа' },
  { currencyId: 'ESP', name: 'ИСПАНСКАЯ ПЕСЕТА' },
  { currencyId: 'ETB', name: 'Эфиопский быр' },
  { currencyId: 'EUR', name: 'Евро', htmlCode: '&#8364;', charCode: [8364] },
  { currencyId: 'FIM', name: 'МАРКА' },
  { currencyId: 'FJD', name: 'Доллар Фиджи' },
  { currencyId: 'FKP', name: 'Фунт Фолклендских островов' },
  { currencyId: 'FRF', name: 'ФРАНЦУЗСКИЙ ФРАНК' },
  { currencyId: 'GBP', name: 'Фунт стерлингов', htmlCode: '&#163;', charCode: [163] },
  { currencyId: 'GEL', name: 'Лари', charCode: [8382] },
  { currencyId: 'GHC', name: 'СЕДИ' },
  { currencyId: 'GHS', name: 'Ганский седи' },
  { currencyId: 'GIP', name: 'Гибралтарский фунт' },
  { currencyId: 'GMD', name: 'Даласи' },
  { currencyId: 'GNF', name: 'Гвинейский франк' },
  { currencyId: 'GRD', name: 'ДРАХМА' },
  { currencyId: 'GTQ', name: 'Кетсаль' },
  { currencyId: 'GWP', name: 'ПЕСО ГВИНЕИ - БИСАУ' },
  { currencyId: 'GYD', name: 'Гайанский доллар' },
  { currencyId: 'HKD', name: 'Гонконгский доллар', charCode: [72, 75, 36] },
  { currencyId: 'HNL', name: 'Лемпира' },
  { currencyId: 'HRK', name: 'Куна' },
  { currencyId: 'HTG', name: 'Гурд' },
  { currencyId: 'HUF', name: 'Форинт' },
  { currencyId: 'IDR', name: 'Рупия' },
  { currencyId: 'IEP', name: 'ИРЛАНДСКИЙ ФУНТ' },
  { currencyId: 'ILS', name: 'Новый израильский шекель' },
  { currencyId: 'INR', name: 'Индийская рупия' },
  { currencyId: 'IQD', name: 'Иракский динар' },
  { currencyId: 'IRR', name: 'Иранский риал' },
  { currencyId: 'ISK', name: 'Исландская крона' },
  { currencyId: 'ITL', name: 'ИТАЛЬЯНСКАЯ ЛИРА' },
  { currencyId: 'JMD', name: 'Ямайский доллар' },
  { currencyId: 'JOD', name: 'Иорданский динар' },
  { currencyId: 'JPY', name: 'Иена', htmlCode: '&#165;', charCode: [165] },
  { currencyId: 'KES', name: 'Кенийский шиллинг' },
  { currencyId: 'KGS', name: 'Сом' },
  { currencyId: 'KHR', name: 'Риель' },
  { currencyId: 'KMF', name: 'Франк Комор' },
  { currencyId: 'KPW', name: 'Северокорейская вона' },
  { currencyId: 'KRW', name: 'Вона' },
  { currencyId: 'KWD', name: 'Кувейтский динар' },
  { currencyId: 'KYD', name: 'Доллар Островов Кайман' },
  { currencyId: 'KZT', name: 'Тенге', htmlCode: '&#8376;', charCode: [8376] },
  { currencyId: 'LAK', name: 'Кип' },
  { currencyId: 'LBP', name: 'Ливанский фунт' },
  { currencyId: 'LKR', name: 'Шри-Ланкийская рупия' },
  { currencyId: 'LRD', name: 'Либерийский доллар' },
  { currencyId: 'LSL', name: 'Лоти' },
  { currencyId: 'LTL', name: 'ЛИТОВСКИЙ ЛИТ' },
  { currencyId: 'LUF', name: 'ЛЮКСЕМБУРГСКИЙ ФРАНК' },
  { currencyId: 'LVL', name: 'ЛАТВИЙСКИЙ ЛАТ' },
  { currencyId: 'LYD', name: 'Ливийский динар' },
  { currencyId: 'MAD', name: 'Марокканский дирхам' },
  { currencyId: 'MDL', name: 'Молдавский лей' },
  { currencyId: 'MGA', name: 'Малагасийский ариари' },
  { currencyId: 'MGF', name: 'МАЛАГАСИЙСКИЙ ФРАНК' },
  { currencyId: 'MKD', name: 'Денар' },
  { currencyId: 'MMK', name: 'Кьят' },
  { currencyId: 'MNT', name: 'Тугрик' },
  { currencyId: 'MOP', name: 'Патака' },
  { currencyId: 'MRO', name: 'Угия' },
  { currencyId: 'MTL', name: 'МАЛЬТИЙСКАЯ ЛИРА' },
  { currencyId: 'MUR', name: 'Маврикийская рупия' },
  { currencyId: 'MVR', name: 'Руфия' },
  { currencyId: 'MWK', name: 'Квача' },
  { currencyId: 'MXN', name: 'Мексиканское песо' },
  { currencyId: 'MYR', name: 'Малайзийский ринггит' },
  { currencyId: 'MZM', name: 'МЕТИКАЛ' },
  { currencyId: 'MZN', name: 'Мозамбикский метикал' },
  { currencyId: 'NAD', name: 'Доллар Намибии' },
  { currencyId: 'NGN', name: 'Найра' },
  { currencyId: 'NIO', name: 'Золотая кордоба' },
  { currencyId: 'NLG', name: 'НИДЕРЛАНДСКИЙ ГУЛЬДЕН' },
  { currencyId: 'NOK', name: 'Норвежская крона', charCode: [107, 114] },
  { currencyId: 'NPR', name: 'Непальская рупия' },
  { currencyId: 'NZD', name: 'Новозеландский доллар', charCode: [78, 90, 36] },
  { currencyId: 'OMR', name: 'Оманский риал' },
  { currencyId: 'PAB', name: 'Бальбоа' },
  { currencyId: 'PEN', name: 'Новый соль' },
  { currencyId: 'PGK', name: 'Кина' },
  { currencyId: 'PHP', name: 'Филиппинское песо' },
  { currencyId: 'PKR', name: 'Пакистанская рупия' },
  { currencyId: 'PLN', name: 'Злотый', charCode: [122, 322] },
  { currencyId: 'PYG', name: 'Гуарани' },
  { currencyId: 'QAR', name: 'Катарский риал' },
  { currencyId: 'ROL', name: 'ЛЕЙ' },
  { currencyId: 'RON', name: 'Румынский лей' },
  { currencyId: 'RSD', name: 'Сербский динар' },
  { currencyId: 'RUB', name: 'Российский рубль', htmlCode: '&#8381;', charCode: [8381] },
  { currencyId: 'RUR', name: 'Российский рубль', htmlCode: '&#8381;', charCode: [8381] },
  { currencyId: 'RWF', name: 'Франк Руанды' },
  { currencyId: 'SAR', name: 'Саудовский риял' },
  { currencyId: 'SBD', name: 'Доллар Соломоновых Островов' },
  { currencyId: 'SCR', name: 'Сейшельская рупия' },
  { currencyId: 'SDD', name: 'СУДАНСКИЙ ДИНАР' },
  { currencyId: 'SDG', name: 'Суданский фунт' },
  { currencyId: 'SEK', name: 'Шведская крона', charCode: [107, 114] },
  { currencyId: 'SGD', name: 'Сингапурский доллар', charCode: [83, 36] },
  { currencyId: 'SHP', name: 'Фунт Святой Елены' },
  { currencyId: 'SIT', name: 'ТОЛАР' },
  { currencyId: 'SKK', name: 'СЛОВАЦКАЯ КРОНА' },
  { currencyId: 'SLL', name: 'Леоне' },
  { currencyId: 'SOS', name: 'Сомалийский шиллинг' },
  { currencyId: 'SRD', name: 'Суринамский доллар' },
  { currencyId: 'SRG', name: 'СУРИНАМСКИЙ ГУЛЬДЕН' },
  { currencyId: 'SSP', name: 'Южносуданский фунт' },
  { currencyId: 'STD', name: 'Добра' },
  { currencyId: 'SVC', name: 'Сальвадорский колон' },
  { currencyId: 'SYP', name: 'Сирийский фунт' },
  { currencyId: 'SZL', name: 'Лилангени' },
  { currencyId: 'THB', name: 'Бат' },
  { currencyId: 'TJS', name: 'Сомони' },
  { currencyId: 'TMM', name: 'МАНАТ' },
  { currencyId: 'TMT', name: 'Новый туркменский манат' },
  { currencyId: 'TND', name: 'Тунисский динар' },
  { currencyId: 'TOP', name: 'Паанга' },
  { currencyId: 'TPE', name: 'ТИМОРСКОЕ ЭСКУДО' },
  { currencyId: 'TRL', name: 'ТУРЕЦКАЯ ЛИРА' },
  { currencyId: 'TRY', name: 'Турецкая лира', charCode: [8378] },
  { currencyId: 'TTD', name: 'Доллар Тринидада и Тобаго' },
  { currencyId: 'TWD', name: 'Новый тайваньский доллар' },
  { currencyId: 'TZS', name: 'Танзанийский шиллинг' },
  { currencyId: 'UAH', name: 'Гривна', charCode: [0x20b4] },
  { currencyId: 'UGX', name: 'Угандийский шиллинг' },
  { currencyId: 'USD', name: 'Доллар США', htmlCode: '&#36;', charCode: [36] },
  { currencyId: 'UYI', name: 'Уругвайское песо в индексированных единицах' },
  { currencyId: 'UYU', name: 'Уругвайское песо' },
  { currencyId: 'UZS', name: 'Узбекский сум' },
  { currencyId: 'VEB', name: 'БОЛИВАР' },
  { currencyId: 'VEF', name: 'Боливар' },
  { currencyId: 'VND', name: 'Донг' },
  { currencyId: 'VUV', name: 'Вату' },
  { currencyId: 'WST', name: 'Тала' },
  { currencyId: 'XAF', name: 'Франк КФА ВЕАС' },
  { currencyId: 'XCD', name: 'Восточно-карибский доллар' },
  { currencyId: 'XDR', name: 'СДР (специальные права заимствования)' },
  { currencyId: 'XOF', name: 'Франк КФА ВСЕАО' },
  { currencyId: 'XPF', name: 'Франк КФП' },
  { currencyId: 'YER', name: 'Йеменский риал' },
  { currencyId: 'YUM', name: 'НОВЫЙ ДИНАР' },
  { currencyId: 'ZAR', name: 'Рэнд', charCode: [82] },
  { currencyId: 'ZMK', name: 'КВАЧА (ЗАМБИЙСКАЯ)' },
  { currencyId: 'ZMW', name: 'Замбийская квача' },
  { currencyId: 'ZWD', name: 'ДОЛЛАР ЗИМБАБВЕ' },
  { currencyId: 'ZWL', name: 'Доллар Зимбабве' },
  { currencyId: 'ВАМ', name: 'Конвертируемая марка' },
  { currencyId: 'РТЕ', name: 'ПОРТУГАЛЬСКОЕ ЭСКУДО' }
];
